# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/model.proto\x12\x05model\"&\n\x13TextGenerateRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x14TextGenerateResponse\x12\r\n\x05reply\x18\x01 \x01(\t2Y\n\x0cModelService\x12I\n\x0cTextGenerate\x12\x1a.model.TextGenerateRequest\x1a\x1b.model.TextGenerateResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTGENERATEREQUEST._serialized_start=29
  _TEXTGENERATEREQUEST._serialized_end=67
  _TEXTGENERATERESPONSE._serialized_start=69
  _TEXTGENERATERESPONSE._serialized_end=106
  _MODELSERVICE._serialized_start=108
  _MODELSERVICE._serialized_end=197
# @@protoc_insertion_point(module_scope)
